-- =========================================================================
-- 의류 상품명에 색상/사이즈 반영 — 같은 이름으로 겹쳐 있던 24개 상품군(264개 SKU).
-- 형식: '상품명 (색상) - 사이즈' (예: Men's Club Polo (Gravity Gray Heather) - M).
-- 색상/사이즈는 딜러 주문서 양식(Sales Order Sheet_Apparel)의 상품코드별 값을 기준으로 했고,
-- 다른 주문서 3건(846행)과 대조해 불일치 0건을 확인했다.
-- 현재 이름이 예상한 이름과 같을 때만 바꾼다(그 사이 수동으로 고친 상품은 건드리지 않음).
-- =========================================================================

-- 실행하면 바뀐 개수(264)가 결과로 나온다. 이미 바뀐 뒤 다시 실행하면 0.
with updated as (
  update products p set name = v.new_name
  from (values
  ('300013', 'Men''s Court Short Sleeve', 'Men''s Court Short Sleeve (Poppy Red) - XS'),
    ('300014', 'Men''s Court Short Sleeve', 'Men''s Court Short Sleeve (Poppy Red) - S'),
    ('300015', 'Men''s Court Short Sleeve', 'Men''s Court Short Sleeve (Poppy Red) - M'),
    ('300016', 'Men''s Court Short Sleeve', 'Men''s Court Short Sleeve (Poppy Red) - L'),
    ('300017', 'Men''s Court Short Sleeve', 'Men''s Court Short Sleeve (Poppy Red) - XXL'),
    ('300018', 'Men''s Court Short Sleeve', 'Men''s Court Short Sleeve (Poppy Red) - XL'),
    ('300039', 'Men''s Court Polo', 'Men''s Court Polo (Blue Breeze) - L'),
    ('300040', 'Men''s Court Polo', 'Men''s Court Polo (Blue Breeze) - M'),
    ('300041', 'Men''s Court Polo', 'Men''s Court Polo (Blue Breeze) - S'),
    ('300042', 'Men''s Court Polo', 'Men''s Court Polo (Blue Breeze) - XL'),
    ('300043', 'Men''s Court Polo', 'Men''s Court Polo (Blue Breeze) - XS'),
    ('300044', 'Men''s Court Polo', 'Men''s Court Polo (Blue Breeze) - XXL'),
    ('300057', 'Men''s Court Long Sleeve', 'Men''s Court Long Sleeve (Sandstone) - L'),
    ('300058', 'Men''s Court Long Sleeve', 'Men''s Court Long Sleeve (Sandstone) - M'),
    ('300059', 'Men''s Court Long Sleeve', 'Men''s Court Long Sleeve (Sandstone) - S'),
    ('300060', 'Men''s Court Long Sleeve', 'Men''s Court Long Sleeve (Sandstone) - XL'),
    ('300061', 'Men''s Court Long Sleeve', 'Men''s Court Long Sleeve (Sandstone) - XS'),
    ('300062', 'Men''s Court Long Sleeve', 'Men''s Court Long Sleeve (Sandstone) - XXL'),
    ('300081', 'Men''s Club Short Sleeve', 'Men''s Club Short Sleeve (Blue Breeze Heather) - L'),
    ('300082', 'Men''s Club Short Sleeve', 'Men''s Club Short Sleeve (Blue Breeze Heather) - M'),
    ('300083', 'Men''s Club Short Sleeve', 'Men''s Club Short Sleeve (Blue Breeze Heather) - S'),
    ('300084', 'Men''s Club Short Sleeve', 'Men''s Club Short Sleeve (Blue Breeze Heather) - XL'),
    ('300085', 'Men''s Club Short Sleeve', 'Men''s Club Short Sleeve (Blue Breeze Heather) - XS'),
    ('300086', 'Men''s Club Short Sleeve', 'Men''s Club Short Sleeve (Blue Breeze Heather) - XXL'),
    ('300087', 'Men''s Club Short Sleeve', 'Men''s Club Short Sleeve (Sandstone Heather) - L'),
    ('300088', 'Men''s Club Short Sleeve', 'Men''s Club Short Sleeve (Sandstone Heather) - M'),
    ('300089', 'Men''s Club Short Sleeve', 'Men''s Club Short Sleeve (Sandstone Heather) - S'),
    ('300090', 'Men''s Club Short Sleeve', 'Men''s Club Short Sleeve (Sandstone Heather) - XL'),
    ('300091', 'Men''s Club Short Sleeve', 'Men''s Club Short Sleeve (Sandstone Heather) - XS'),
    ('300092', 'Men''s Club Short Sleeve', 'Men''s Club Short Sleeve (Sandstone Heather) - XXL'),
    ('300099', 'Men''s Club Polo', 'Men''s Club Polo (Black) - L'),
    ('300100', 'Men''s Club Polo', 'Men''s Club Polo (Black) - M'),
    ('300101', 'Men''s Club Polo', 'Men''s Club Polo (Black) - S'),
    ('300102', 'Men''s Club Polo', 'Men''s Club Polo (Black) - XL'),
    ('300103', 'Men''s Club Polo', 'Men''s Club Polo (Black) - XS'),
    ('300104', 'Men''s Club Polo', 'Men''s Club Polo (Black) - XXL'),
    ('300105', 'Men''s Club Polo', 'Men''s Club Polo (Navy Heather) - L'),
    ('300106', 'Men''s Club Polo', 'Men''s Club Polo (Navy Heather) - M'),
    ('300107', 'Men''s Club Polo', 'Men''s Club Polo (Navy Heather) - S'),
    ('300108', 'Men''s Club Polo', 'Men''s Club Polo (Navy Heather) - XL'),
    ('300109', 'Men''s Club Polo', 'Men''s Club Polo (Navy Heather) - XXL'),
    ('300110', 'Men''s Club Polo', 'Men''s Club Polo (Navy Heather) - XS'),
    ('300111', 'Men''s Club Polo', 'Men''s Club Polo (Tropic Tide Heather) - L'),
    ('300112', 'Men''s Club Polo', 'Men''s Club Polo (Tropic Tide Heather) - M'),
    ('300113', 'Men''s Club Polo', 'Men''s Club Polo (Tropic Tide Heather) - S'),
    ('300114', 'Men''s Club Polo', 'Men''s Club Polo (Tropic Tide Heather) - XL'),
    ('300115', 'Men''s Club Polo', 'Men''s Club Polo (Tropic Tide Heather) - XS'),
    ('300116', 'Men''s Club Polo', 'Men''s Club Polo (Tropic Tide Heather) - XXL'),
    ('300117', 'Men''s Club Polo', 'Men''s Club Polo (Gravity Gray Heather) - L'),
    ('300118', 'Men''s Club Polo', 'Men''s Club Polo (Gravity Gray Heather) - M'),
    ('300119', 'Men''s Club Polo', 'Men''s Club Polo (Gravity Gray Heather) - S'),
    ('300120', 'Men''s Club Polo', 'Men''s Club Polo (Gravity Gray Heather) - XL'),
    ('300121', 'Men''s Club Polo', 'Men''s Club Polo (Gravity Gray Heather) - XS'),
    ('300122', 'Men''s Club Polo', 'Men''s Club Polo (Gravity Gray Heather) - XXL'),
    ('300123', 'Men''s Club Polo', 'Men''s Club Polo (White) - L'),
    ('300124', 'Men''s Club Polo', 'Men''s Club Polo (White) - M'),
    ('300125', 'Men''s Club Polo', 'Men''s Club Polo (White) - S'),
    ('300126', 'Men''s Club Polo', 'Men''s Club Polo (White) - XL'),
    ('300127', 'Men''s Club Polo', 'Men''s Club Polo (White) - XS'),
    ('300128', 'Men''s Club Polo', 'Men''s Club Polo (White) - XXL'),
    ('300141', 'Men''s Quarter Zip Pullover', 'Men''s Quarter Zip Pullover (Sandstone Heather) - L'),
    ('300142', 'Men''s Quarter Zip Pullover', 'Men''s Quarter Zip Pullover (Sandstone Heather) - M'),
    ('300143', 'Men''s Quarter Zip Pullover', 'Men''s Quarter Zip Pullover (Sandstone Heather) - S'),
    ('300144', 'Men''s Quarter Zip Pullover', 'Men''s Quarter Zip Pullover (Sandstone Heather) - XL'),
    ('300145', 'Men''s Quarter Zip Pullover', 'Men''s Quarter Zip Pullover (Sandstone Heather) - XS'),
    ('300146', 'Men''s Quarter Zip Pullover', 'Men''s Quarter Zip Pullover (Sandstone Heather) - XXL'),
    ('300177', 'Men''s Woven Shorts 7in', 'Men''s Woven Shorts 7in (Poppy Red) - L'),
    ('300178', 'Men''s Woven Shorts 7in', 'Men''s Woven Shorts 7in (Poppy Red) - M'),
    ('300179', 'Men''s Woven Shorts 7in', 'Men''s Woven Shorts 7in (Poppy Red) - S'),
    ('300180', 'Men''s Woven Shorts 7in', 'Men''s Woven Shorts 7in (Poppy Red) - XL'),
    ('300181', 'Men''s Woven Shorts 7in', 'Men''s Woven Shorts 7in (Poppy Red) - XS'),
    ('300182', 'Men''s Woven Shorts 7in', 'Men''s Woven Shorts 7in (Poppy Red) - XXL'),
    ('300207', 'Men''s Woven Shorts 5in', 'Men''s Woven Shorts 5in (Poppy Red) - L'),
    ('300208', 'Men''s Woven Shorts 5in', 'Men''s Woven Shorts 5in (Poppy Red) - M'),
    ('300209', 'Men''s Woven Shorts 5in', 'Men''s Woven Shorts 5in (Poppy Red) - S'),
    ('300210', 'Men''s Woven Shorts 5in', 'Men''s Woven Shorts 5in (Poppy Red) - XL'),
    ('300211', 'Men''s Woven Shorts 5in', 'Men''s Woven Shorts 5in (Poppy Red) - XS'),
    ('300212', 'Men''s Woven Shorts 5in', 'Men''s Woven Shorts 5in (Poppy Red) - XXL'),
    ('300219', 'Men''s Club Printed Polo', 'Men''s Club Printed Polo (Safari Leopard - White) - L'),
    ('300220', 'Men''s Club Printed Polo', 'Men''s Club Printed Polo (Safari Leopard - White) - M'),
    ('300221', 'Men''s Club Printed Polo', 'Men''s Club Printed Polo (Safari Leopard - White) - S'),
    ('300222', 'Men''s Club Printed Polo', 'Men''s Club Printed Polo (Safari Leopard - White) - XL'),
    ('300223', 'Men''s Club Printed Polo', 'Men''s Club Printed Polo (Safari Leopard - White) - XS'),
    ('300224', 'Men''s Club Printed Polo', 'Men''s Club Printed Polo (Safari Leopard - White) - XXL'),
    ('300225', 'Men''s Club Printed Polo', 'Men''s Club Printed Polo (Serpentine - Charcoal Gray) - L'),
    ('300226', 'Men''s Club Printed Polo', 'Men''s Club Printed Polo (Serpentine - Charcoal Gray) - M'),
    ('300227', 'Men''s Club Printed Polo', 'Men''s Club Printed Polo (Serpentine - Charcoal Gray) - S'),
    ('300228', 'Men''s Club Printed Polo', 'Men''s Club Printed Polo (Serpentine - Charcoal Gray) - XL'),
    ('300229', 'Men''s Club Printed Polo', 'Men''s Club Printed Polo (Serpentine - Charcoal Gray) - XS'),
    ('300230', 'Men''s Club Printed Polo', 'Men''s Club Printed Polo (Serpentine - Charcoal Gray) - XXL'),
    ('300255', 'Men''s Woven 2-in-1 Shorts', 'Men''s Woven 2-in-1 Shorts (Latte) - L'),
    ('300256', 'Men''s Woven 2-in-1 Shorts', 'Men''s Woven 2-in-1 Shorts (Latte) - M'),
    ('300257', 'Men''s Woven 2-in-1 Shorts', 'Men''s Woven 2-in-1 Shorts (Latte) - S'),
    ('300258', 'Men''s Woven 2-in-1 Shorts', 'Men''s Woven 2-in-1 Shorts (Latte) - XL'),
    ('300259', 'Men''s Woven 2-in-1 Shorts', 'Men''s Woven 2-in-1 Shorts (Latte) - XS'),
    ('300260', 'Men''s Woven 2-in-1 Shorts', 'Men''s Woven 2-in-1 Shorts (Latte) - XXL'),
    ('300267', 'Men''s Club Shorts', 'Men''s Club Shorts (Black) - L'),
    ('300268', 'Men''s Club Shorts', 'Men''s Club Shorts (Black) - M'),
    ('300269', 'Men''s Club Shorts', 'Men''s Club Shorts (Black) - S'),
    ('300270', 'Men''s Club Shorts', 'Men''s Club Shorts (Black) - XL'),
    ('300271', 'Men''s Club Shorts', 'Men''s Club Shorts (Black) - XS'),
    ('300272', 'Men''s Club Shorts', 'Men''s Club Shorts (Black) - XXL'),
    ('300273', 'Men''s Club Shorts', 'Men''s Club Shorts (Navy) - L'),
    ('300274', 'Men''s Club Shorts', 'Men''s Club Shorts (Navy) - M'),
    ('300275', 'Men''s Club Shorts', 'Men''s Club Shorts (Navy) - S'),
    ('300276', 'Men''s Club Shorts', 'Men''s Club Shorts (Navy) - XL'),
    ('300277', 'Men''s Club Shorts', 'Men''s Club Shorts (Navy) - XS'),
    ('300278', 'Men''s Club Shorts', 'Men''s Club Shorts (Navy) - XXL'),
    ('300279', 'Men''s Club Shorts', 'Men''s Club Shorts (Sandstone) - L'),
    ('300280', 'Men''s Club Shorts', 'Men''s Club Shorts (Sandstone) - M'),
    ('300281', 'Men''s Club Shorts', 'Men''s Club Shorts (Sandstone) - S'),
    ('300282', 'Men''s Club Shorts', 'Men''s Club Shorts (Sandstone) - XL'),
    ('300283', 'Men''s Club Shorts', 'Men''s Club Shorts (Sandstone) - XS'),
    ('300284', 'Men''s Club Shorts', 'Men''s Club Shorts (Sandstone) - XXL'),
    ('300285', 'Men''s Club Joggers', 'Men''s Club Joggers (Black) - L'),
    ('300286', 'Men''s Club Joggers', 'Men''s Club Joggers (Black) - M'),
    ('300287', 'Men''s Club Joggers', 'Men''s Club Joggers (Black) - S'),
    ('300288', 'Men''s Club Joggers', 'Men''s Club Joggers (Black) - XL'),
    ('300289', 'Men''s Club Joggers', 'Men''s Club Joggers (Black) - XS'),
    ('300290', 'Men''s Club Joggers', 'Men''s Club Joggers (Black) - XXL'),
    ('300291', 'Men''s Club Joggers', 'Men''s Club Joggers (Navy) - L'),
    ('300292', 'Men''s Club Joggers', 'Men''s Club Joggers (Navy) - M'),
    ('300293', 'Men''s Club Joggers', 'Men''s Club Joggers (Navy) - S'),
    ('300294', 'Men''s Club Joggers', 'Men''s Club Joggers (Navy) - XL'),
    ('300295', 'Men''s Club Joggers', 'Men''s Club Joggers (Navy) - XS'),
    ('300296', 'Men''s Club Joggers', 'Men''s Club Joggers (Navy) - XXL'),
    ('300297', 'Men''s Club Joggers', 'Men''s Club Joggers (Latte) - L'),
    ('300298', 'Men''s Club Joggers', 'Men''s Club Joggers (Latte) - M'),
    ('300299', 'Men''s Club Joggers', 'Men''s Club Joggers (Latte) - S'),
    ('300300', 'Men''s Club Joggers', 'Men''s Club Joggers (Latte) - XL'),
    ('300301', 'Men''s Club Joggers', 'Men''s Club Joggers (Latte) - XS'),
    ('300302', 'Men''s Club Joggers', 'Men''s Club Joggers (Latte) - XXL'),
    ('300315', 'Women''s Court Tank', 'Women''s Court Tank (Blue Breeze) - L'),
    ('300316', 'Women''s Court Tank', 'Women''s Court Tank (Blue Breeze) - M'),
    ('300317', 'Women''s Court Tank', 'Women''s Court Tank (Blue Breeze) - S'),
    ('300318', 'Women''s Court Tank', 'Women''s Court Tank (Blue Breeze) - XL'),
    ('300319', 'Women''s Court Tank', 'Women''s Court Tank (Blue Breeze) - XS'),
    ('300320', 'Women''s Court Tank', 'Women''s Court Tank (Blue Breeze) - XXL'),
    ('300345', 'Women''s Court Crop Tee', 'Women''s Court Crop Tee (Poppy Red) - L'),
    ('300346', 'Women''s Court Crop Tee', 'Women''s Court Crop Tee (Poppy Red) - M'),
    ('300347', 'Women''s Court Crop Tee', 'Women''s Court Crop Tee (Poppy Red) - S'),
    ('300348', 'Women''s Court Crop Tee', 'Women''s Court Crop Tee (Poppy Red) - XL'),
    ('300349', 'Women''s Court Crop Tee', 'Women''s Court Crop Tee (Poppy Red) - XS'),
    ('300350', 'Women''s Court Crop Tee', 'Women''s Court Crop Tee (Poppy Red) - XXL'),
    ('300375', 'Women''s Club Short Sleeve Crew Neck', 'Women''s Club Short Sleeve Crew Neck (Blue Breeze Heather) - L'),
    ('300376', 'Women''s Club Short Sleeve Crew Neck', 'Women''s Club Short Sleeve Crew Neck (Blue Breeze Heather) - M'),
    ('300377', 'Women''s Club Short Sleeve Crew Neck', 'Women''s Club Short Sleeve Crew Neck (Blue Breeze Heather) - S'),
    ('300378', 'Women''s Club Short Sleeve Crew Neck', 'Women''s Club Short Sleeve Crew Neck (Blue Breeze Heather) - XL'),
    ('300379', 'Women''s Club Short Sleeve Crew Neck', 'Women''s Club Short Sleeve Crew Neck (Blue Breeze Heather) - XS'),
    ('300380', 'Women''s Club Short Sleeve Crew Neck', 'Women''s Club Short Sleeve Crew Neck (Blue Breeze Heather) - XXL'),
    ('300381', 'Women''s Club Short Sleeve Crew Neck', 'Women''s Club Short Sleeve Crew Neck (Sandstone Heather) - L'),
    ('300382', 'Women''s Club Short Sleeve Crew Neck', 'Women''s Club Short Sleeve Crew Neck (Sandstone Heather) - M'),
    ('300383', 'Women''s Club Short Sleeve Crew Neck', 'Women''s Club Short Sleeve Crew Neck (Sandstone Heather) - S'),
    ('300384', 'Women''s Club Short Sleeve Crew Neck', 'Women''s Club Short Sleeve Crew Neck (Sandstone Heather) - XL'),
    ('300385', 'Women''s Club Short Sleeve Crew Neck', 'Women''s Club Short Sleeve Crew Neck (Sandstone Heather) - XS'),
    ('300386', 'Women''s Club Short Sleeve Crew Neck', 'Women''s Club Short Sleeve Crew Neck (Sandstone Heather) - XXL'),
    ('300387', 'Women''s Club Short Sleeve Crew Neck', 'Women''s Club Short Sleeve Crew Neck (Purple Dusk) - L'),
    ('300388', 'Women''s Club Short Sleeve Crew Neck', 'Women''s Club Short Sleeve Crew Neck (Purple Dusk) - M'),
    ('300389', 'Women''s Club Short Sleeve Crew Neck', 'Women''s Club Short Sleeve Crew Neck (Purple Dusk) - S'),
    ('300390', 'Women''s Club Short Sleeve Crew Neck', 'Women''s Club Short Sleeve Crew Neck (Purple Dusk) - XL'),
    ('300391', 'Women''s Club Short Sleeve Crew Neck', 'Women''s Club Short Sleeve Crew Neck (Purple Dusk) - XS'),
    ('300392', 'Women''s Club Short Sleeve Crew Neck', 'Women''s Club Short Sleeve Crew Neck (Purple Dusk) - XXL'),
    ('300393', 'Women''s Club Short Sleeve Crew Neck', 'Women''s Club Short Sleeve Crew Neck (White) - L'),
    ('300394', 'Women''s Club Short Sleeve Crew Neck', 'Women''s Club Short Sleeve Crew Neck (White) - M'),
    ('300395', 'Women''s Club Short Sleeve Crew Neck', 'Women''s Club Short Sleeve Crew Neck (White) - S'),
    ('300396', 'Women''s Club Short Sleeve Crew Neck', 'Women''s Club Short Sleeve Crew Neck (White) - XL'),
    ('300397', 'Women''s Club Short Sleeve Crew Neck', 'Women''s Club Short Sleeve Crew Neck (White) - XS'),
    ('300398', 'Women''s Club Short Sleeve Crew Neck', 'Women''s Club Short Sleeve Crew Neck (White) - XXL'),
    ('300429', 'Women''s Club Novelty Polo Dress', 'Women''s Club Novelty Polo Dress (Passion Purple) - L'),
    ('300430', 'Women''s Club Novelty Polo Dress', 'Women''s Club Novelty Polo Dress (Passion Purple) - M'),
    ('300431', 'Women''s Club Novelty Polo Dress', 'Women''s Club Novelty Polo Dress (Passion Purple) - S'),
    ('300432', 'Women''s Club Novelty Polo Dress', 'Women''s Club Novelty Polo Dress (Passion Purple) - XL'),
    ('300433', 'Women''s Club Novelty Polo Dress', 'Women''s Club Novelty Polo Dress (Passion Purple) - XS'),
    ('300434', 'Women''s Club Novelty Polo Dress', 'Women''s Club Novelty Polo Dress (Passion Purple) - XXL'),
    ('300435', 'Women''s Club Novelty Polo Dress', 'Women''s Club Novelty Polo Dress (White) - L'),
    ('300436', 'Women''s Club Novelty Polo Dress', 'Women''s Club Novelty Polo Dress (White) - M'),
    ('300437', 'Women''s Club Novelty Polo Dress', 'Women''s Club Novelty Polo Dress (White) - S'),
    ('300438', 'Women''s Club Novelty Polo Dress', 'Women''s Club Novelty Polo Dress (White) - XL'),
    ('300439', 'Women''s Club Novelty Polo Dress', 'Women''s Club Novelty Polo Dress (White) - XS'),
    ('300440', 'Women''s Club Novelty Polo Dress', 'Women''s Club Novelty Polo Dress (White) - XXL'),
    ('300453', 'Women''s Pickleball Skort', 'Women''s Pickleball Skort (Blue Breeze) - L'),
    ('300454', 'Women''s Pickleball Skort', 'Women''s Pickleball Skort (Blue Breeze) - M'),
    ('300455', 'Women''s Pickleball Skort', 'Women''s Pickleball Skort (Blue Breeze) - S'),
    ('300456', 'Women''s Pickleball Skort', 'Women''s Pickleball Skort (Blue Breeze) - XL'),
    ('300457', 'Women''s Pickleball Skort', 'Women''s Pickleball Skort (Blue Breeze) - XS'),
    ('300458', 'Women''s Pickleball Skort', 'Women''s Pickleball Skort (Blue Breeze) - XXL'),
    ('300466', 'Women''s Club Skort', 'Women''s Club Skort (Navy) - L'),
    ('300467', 'Women''s Club Skort', 'Women''s Club Skort (Navy) - M'),
    ('300468', 'Women''s Club Skort', 'Women''s Club Skort (Navy) - S'),
    ('300469', 'Women''s Club Skort', 'Women''s Club Skort (Navy) - XL'),
    ('300470', 'Women''s Club Skort', 'Women''s Club Skort (Navy) - XS'),
    ('300471', 'Women''s Club Skort', 'Women''s Club Skort (Navy) - XXL'),
    ('300472', 'Women''s Club Skort', 'Women''s Club Skort (Latte) - L'),
    ('300473', 'Women''s Club Skort', 'Women''s Club Skort (Latte) - M'),
    ('300474', 'Women''s Club Skort', 'Women''s Club Skort (Latte) - S'),
    ('300475', 'Women''s Club Skort', 'Women''s Club Skort (Latte) - XL'),
    ('300476', 'Women''s Club Skort', 'Women''s Club Skort (Latte) - XS'),
    ('300477', 'Women''s Club Skort', 'Women''s Club Skort (Latte) - XXL'),
    ('300478', 'Women''s Club Skort', 'Women''s Club Skort (White) - L'),
    ('300479', 'Women''s Club Skort', 'Women''s Club Skort (White) - M'),
    ('300480', 'Women''s Club Skort', 'Women''s Club Skort (White) - S'),
    ('300481', 'Women''s Club Skort', 'Women''s Club Skort (White) - XS'),
    ('300482', 'Women''s Club Skort', 'Women''s Club Skort (White) - XL'),
    ('300483', 'Women''s Club Skort', 'Women''s Club Skort (White) - XXL'),
    ('300496', 'Women''s Court Woven Shorts', 'Women''s Court Woven Shorts (Passion Purple) - L'),
    ('300497', 'Women''s Court Woven Shorts', 'Women''s Court Woven Shorts (Passion Purple) - S'),
    ('300498', 'Women''s Court Woven Shorts', 'Women''s Court Woven Shorts (Passion Purple) - M'),
    ('300499', 'Women''s Court Woven Shorts', 'Women''s Court Woven Shorts (Passion Purple) - XL'),
    ('300500', 'Women''s Court Woven Shorts', 'Women''s Court Woven Shorts (Passion Purple) - XS'),
    ('300501', 'Women''s Court Woven Shorts', 'Women''s Court Woven Shorts (Passion Purple) - XXL'),
    ('300529', 'Women''s Court 2-in-1 Shorts', 'Women''s Court 2-in-1 Shorts (Poppy Red) - L'),
    ('300530', 'Women''s Court 2-in-1 Shorts', 'Women''s Court 2-in-1 Shorts (Poppy Red) - M'),
    ('300531', 'Women''s Court 2-in-1 Shorts', 'Women''s Court 2-in-1 Shorts (Poppy Red) - S'),
    ('300532', 'Women''s Court 2-in-1 Shorts', 'Women''s Court 2-in-1 Shorts (Poppy Red) - XL'),
    ('300533', 'Women''s Court 2-in-1 Shorts', 'Women''s Court 2-in-1 Shorts (Poppy Red) - XS'),
    ('300534', 'Women''s Court 2-in-1 Shorts', 'Women''s Court 2-in-1 Shorts (Poppy Red) - XXL'),
    ('300541', 'Women''s Court Woven Printed Shorts', 'Women''s Court Woven Printed Shorts (Safari Leopard - White) - L'),
    ('300542', 'Women''s Court Woven Printed Shorts', 'Women''s Court Woven Printed Shorts (Safari Leopard - White) - M'),
    ('300543', 'Women''s Court Woven Printed Shorts', 'Women''s Court Woven Printed Shorts (Safari Leopard - White) - S'),
    ('300544', 'Women''s Court Woven Printed Shorts', 'Women''s Court Woven Printed Shorts (Safari Leopard - White) - XL'),
    ('300545', 'Women''s Court Woven Printed Shorts', 'Women''s Court Woven Printed Shorts (Safari Leopard - White) - XS'),
    ('300546', 'Women''s Court Woven Printed Shorts', 'Women''s Court Woven Printed Shorts (Safari Leopard - White) - XXL'),
    ('300547', 'Women''s Pickleball Printed Skort', 'Women''s Pickleball Printed Skort (Serpentine - Passion Purple) - XS'),
    ('300548', 'Women''s Pickleball Printed Skort', 'Women''s Pickleball Printed Skort (Serpentine - Passion Purple) - S'),
    ('300549', 'Women''s Pickleball Printed Skort', 'Women''s Pickleball Printed Skort (Serpentine - Passion Purple) - M'),
    ('300550', 'Women''s Pickleball Printed Skort', 'Women''s Pickleball Printed Skort (Serpentine - Passion Purple) - L'),
    ('300551', 'Women''s Pickleball Printed Skort', 'Women''s Pickleball Printed Skort (Serpentine - Passion Purple) - XL'),
    ('300552', 'Women''s Pickleball Printed Skort', 'Women''s Pickleball Printed Skort (Serpentine - Passion Purple) - XXL'),
    ('300559', 'Women''s Pickleball Skort 15in', 'Women''s Pickleball Skort 15in (Black) - XS'),
    ('300560', 'Women''s Pickleball Skort 15in', 'Women''s Pickleball Skort 15in (Black) - S'),
    ('300561', 'Women''s Pickleball Skort 15in', 'Women''s Pickleball Skort 15in (Black) - M'),
    ('300562', 'Women''s Pickleball Skort 15in', 'Women''s Pickleball Skort 15in (Black) - L'),
    ('300563', 'Women''s Pickleball Skort 15in', 'Women''s Pickleball Skort 15in (Black) - XL'),
    ('300564', 'Women''s Pickleball Skort 15in', 'Women''s Pickleball Skort 15in (Black) - XXL'),
    ('300565', 'Women''s Pickleball Skort 15in', 'Women''s Pickleball Skort 15in (Navy) - XS'),
    ('300566', 'Women''s Pickleball Skort 15in', 'Women''s Pickleball Skort 15in (Navy) - S'),
    ('300567', 'Women''s Pickleball Skort 15in', 'Women''s Pickleball Skort 15in (Navy) - M'),
    ('300568', 'Women''s Pickleball Skort 15in', 'Women''s Pickleball Skort 15in (Navy) - L'),
    ('300569', 'Women''s Pickleball Skort 15in', 'Women''s Pickleball Skort 15in (Navy) - XL'),
    ('300570', 'Women''s Pickleball Skort 15in', 'Women''s Pickleball Skort 15in (Navy) - XXL'),
    ('300571', 'Women''s Pickleball Skort 15in', 'Women''s Pickleball Skort 15in (White) - XS'),
    ('300572', 'Women''s Pickleball Skort 15in', 'Women''s Pickleball Skort 15in (White) - S'),
    ('300573', 'Women''s Pickleball Skort 15in', 'Women''s Pickleball Skort 15in (White) - M'),
    ('300574', 'Women''s Pickleball Skort 15in', 'Women''s Pickleball Skort 15in (White) - L'),
    ('300575', 'Women''s Pickleball Skort 15in', 'Women''s Pickleball Skort 15in (White) - XL'),
    ('300576', 'Women''s Pickleball Skort 15in', 'Women''s Pickleball Skort 15in (White) - XXL'),
    ('300577', 'Women''s Club Sleeveless Polo', 'Women''s Club Sleeveless Polo (Navy Heather) - L'),
    ('300578', 'Women''s Club Sleeveless Polo', 'Women''s Club Sleeveless Polo (Navy Heather) - M'),
    ('300579', 'Women''s Club Sleeveless Polo', 'Women''s Club Sleeveless Polo (Navy Heather) - S'),
    ('300580', 'Women''s Club Sleeveless Polo', 'Women''s Club Sleeveless Polo (Navy Heather) - XL'),
    ('300581', 'Women''s Club Sleeveless Polo', 'Women''s Club Sleeveless Polo (Navy Heather) - XS'),
    ('300582', 'Women''s Club Sleeveless Polo', 'Women''s Club Sleeveless Polo (Navy Heather) - XXL'),
    ('300583', 'Women''s Club Sleeveless Polo', 'Women''s Club Sleeveless Polo (Sandstone Heather) - L'),
    ('300584', 'Women''s Club Sleeveless Polo', 'Women''s Club Sleeveless Polo (Sandstone Heather) - M'),
    ('300585', 'Women''s Club Sleeveless Polo', 'Women''s Club Sleeveless Polo (Sandstone Heather) - S'),
    ('300586', 'Women''s Club Sleeveless Polo', 'Women''s Club Sleeveless Polo (Sandstone Heather) - XL'),
    ('300587', 'Women''s Club Sleeveless Polo', 'Women''s Club Sleeveless Polo (Sandstone Heather) - XS'),
    ('300588', 'Women''s Club Sleeveless Polo', 'Women''s Club Sleeveless Polo (Sandstone Heather) - XXL'),
    ('300589', 'Women''s Club Sleeveless Polo', 'Women''s Club Sleeveless Polo (Passion Purple) - L'),
    ('300590', 'Women''s Club Sleeveless Polo', 'Women''s Club Sleeveless Polo (Passion Purple) - M'),
    ('300591', 'Women''s Club Sleeveless Polo', 'Women''s Club Sleeveless Polo (Passion Purple) - S'),
    ('300592', 'Women''s Club Sleeveless Polo', 'Women''s Club Sleeveless Polo (Passion Purple) - XL'),
    ('300593', 'Women''s Club Sleeveless Polo', 'Women''s Club Sleeveless Polo (Passion Purple) - XS'),
    ('300594', 'Women''s Club Sleeveless Polo', 'Women''s Club Sleeveless Polo (Passion Purple) - XXL')
  ) as v(sku, old_name, new_name)
  where p.sku = v.sku and p.name = v.old_name
  returning p.sku
)
select count(*) as renamed from updated;
